styles/Home.module.css
styles/globals.css

Co-authored-by: Miah <78933903+miahbates@users.noreply.github.com>
Co-authored-by: Milly <62570785+millipede-cpu@users.noreply.github.com>
Co-authored-by: Juliette <53294140+julietteorpen@users.noreply.github.com>

Add CSS styles

---

components/ProductCard.jsx
components/ProductDisplay.jsx
components/styled-components/StyledLink.jsx
components/styled-components/StyledProductCard.jsx
styles/globals.css

- Render all products in cards
- To do: add filter tags to each card

Product card

---

pages/about-page.js

Co-authored-by: Juliette <53294140+julietteorpen@users.noreply.github.com>
Co-authored-by: Orian <77785778+OrianP@users.noreply.github.com>
Co-authored-by: Miah <78933903+miahbates@users.noreply.github.com>

Made About Page with link back to home and icons similar to Figma design

---

components/GridGallery.jsx
components/IntroLusan.jsx
components/SearchBar.jsx
components/styled-components/StyledIntro.jsx
components/styled-components/StyledSearchBar.jsx
pages/about-page.js
pages/index.js
styles/globals.css

* styling started for landing page 
* flex on mobile and grids for larger screens

Style landing

---

components/Layout.jsx
components/nav/burger.jsx
components/nav/leftNav.jsx
components/nav/navbar.jsx
pages/_app.js
styles/globals.css

- finished animating burger menu component
- tried to figure out how to make the nav menu disappear when moving to a new page
Co-authored by: [Miah](https://github.com/miahbates)
Co-authored by: [Milly](https://github.com/millipede-cpu)
Co-authored-by:[Orian](https://github.com/OrianP)

burger menu animation

---

next.config.js
package-lock.json
package.json
pages/contact-page.js
styles/globals.css

- grow image added to public folder 
- social media icons added
- instagram logo goes to Grow Lusan Instagram when clicked
- envelope icon and email goes to grow lusan email

Contact page with hyperlinks to grow lusan instagram and email

---

components/ConditionFilters.jsx
components/PriceFilters.jsx
components/ProductDisplay.jsx
helper-functions.js
pages/all-seeds.js

- Individual states for type conditions
- Start of price filters

Condition filters

---

components/ConditionFilters.jsx
components/ProductDisplay.jsx
database/database-functions.js
pages/all-seeds.js

Condition filters finish

---

components/ProductDisplay.jsx

* Filter by price at the moment filters by first price in products array.
* Ammended .filter logic to check product.providers[0].price to access the price
Relates #9

Price filtering completed

---

components/Layout.jsx
components/ProductDisplay.jsx
components/styled-components/StyledProductPage.jsx
pages/products/[variety].js

Basic styling of product page
Carousel to be added on sprint 2
Related #30

Style product page

---

REPORT.md

Update project documentation

---

components/Layout.jsx
components/SearchBar.jsx
components/context/SearchbarContext.jsx
package-lock.json
package.json
pages/all-seeds.js
pages/index.js

created context folder with SearchbarContext, wrapped layout in SearchBar.Provider component so that searchbar context available globally and the searchterm updates onChange of searchbar input
Relates #60
Co-authored-by: Milly <62570785+millipede-cpu@users.noreply.github.com>

created SearchbarContext

---

components/nav/burger.jsx
components/styled-components/StyledNavLink.jsx
styles/globals.css

* now responsive
* changed font
* aligned icons
* centered search and wishlist icon
Relates #56

Styling nav bar

---

components/ProductCard.jsx
components/ProductDisplay.jsx
components/WishlistToggle.jsx
components/styled-components/StyledLink.jsx
components/styled-components/StyledProductCard.jsx
pages/all-seeds.js
pages/products/[variety].js
styles/globals.css

* desktop styled 
* clickable cards to dynamic product pages

Style product cards desktop

---

components/ProductCard.jsx
components/WishlistToggle.jsx
components/styled-components/StyledProductCard.jsx
components/styled-components/StyledToggleButton.jsx
pages/all-seeds.js
pages/wishlist.js

- Run a useEffect when WishlistToggle renders
- Check if product is already in wishList and set state
of hearToggle accordingly
- Heart icon state persists on page refresh and navigation

Heart icon persist

---

components/GridGallery.jsx
components/SearchBar.jsx
components/styled-components/StyledGridCover.jsx
components/styled-components/StyledGridTile.jsx
styles/globals.css

updated global css so that background images are darkened but text remains same colour by using ::before
Relates #57

created grid cover to darkened grid tiles on landing page

---

components/Bin.jsx
components/WishlistToggle.jsx
helper-functions.js
pages/all-seeds.js
pages/wishlist.js

- Create helper functions for adding/removing/reading from local storage
- Replace existing code with helper functions

Local storage refactor

---

components/styled-components/StyledFooter.jsx
components/styled-components/StyledGridTile.jsx
components/styled-components/StyledIntro.jsx
components/styled-components/StyledLink.jsx
components/styled-components/StyledProductCard.jsx
components/styled-components/StyledProductPage.jsx
components/styled-components/StyledSearchBar.jsx
components/styled-components/StyledTab.jsx
pages/_document.js
styles/globals.css

got rid of second link in document file and ensured all fonts are using css variables

updated fonts

---

cypress.json
cypress/integration/tests.js

Write homepage tests

---

components/CategoryFilters.jsx
components/ConditionFilters.jsx
components/SearchBar.jsx
components/styled-components/StyledFilter.jsx
components/styled-components/StyledNavLink.jsx
components/styled-components/StyledSearchBar.jsx
styles/globals.css

started cat filters, added clear filter button

---

cypress/integration/tests.js

Write route and search + filters tests

---

components/nav/burger.jsx
components/styled-components/StyledComparisonGrid.jsx
components/styled-components/StyledProductPage.jsx
pages/products/[variety].js
styles/globals.css

* mobile and laptop design done
* fixed arrow on carousel to not extend past the image
* adjusted font sizes
* added links to comparison tables
* width 50% and centered on larger screens
closes #52

Individual product page styled

---

components/nav/burger.jsx

Link logo to homepage

---

components/IntroLusan.jsx
components/styled-components/StyledGridCover.jsx
components/styled-components/StyledIntro.jsx
components/styled-components/StyledNavLink.jsx
components/styled-components/StyledSearchBar.jsx
pages/products/[variety].js
styles/globals.css

* centered images on homepage
* images different viewports on different screen sizes
* links to seeds now working
* added bottom border to nav bar
* added margin to body
relates #112

Finishing touches

---

components/SearchBar.jsx
components/styled-components/StyledSearchBar.jsx

- Wrap search bar in form
- Redirect on submit
Relates #115
Co-authored-by: Juliette <53294140+julietteorpen@users.noreply.github.com>

Allow search bar to be keyboard interactive

---

components/Layout.jsx
components/WishlistCounter.jsx
components/styled-components/StyledProductCard.jsx
styles/globals.css

- Add wishlist counter
- Fix wishlist spacing

Wishlist count

---

components/WishlistCounter.jsx

Change counter color
